# 生产环境配置（prod）
# 说明：
# - 推荐用于线上/预发环境
# - 可通过 APP_CONF 或启动参数 -conf 指定本文件
#   示例：APP_CONF=config/prod.yml go run ./cmd/server
# - 建议将 env 设置为 prod，以便日志等按生产策略运行
# - 生产环境请避免在配置中保留明文密钥与密码（可用环境变量或密钥管理服务）
env: local
http:
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: 1234
data:
  mysql:
    user: root:123456@tcp(127.0.0.1:3380)/user?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6350
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: info
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30              # 日志文件最多保存多少个备份
  max_age: 7                   #  文件最多保存多少天
  max_size: 1024               #  每个日志文件保存的最大尺寸 单位：M
  compress: true               # 是否压缩